# Generated by Django 4.2.5 on 2023-11-04 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmortizacionPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del registro')),
                ('anio', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('mes', models.IntegerField(blank=True, null=True, verbose_name='Mes')),
                ('monto_inicial_mes', models.FloatField(blank=True, default=0, null=True, verbose_name='Monto inicial')),
                ('monto_final_mes', models.FloatField(blank=True, default=0, null=True, verbose_name='Monto final')),
                ('monto_real', models.FloatField(blank=True, default=0, null=True, verbose_name='Monto a cancelar')),
            ],
            options={
                'verbose_name': 'Amortización de préstamo',
                'verbose_name_plural': 'Amortizaciones de préstamos',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del registro')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Área u oficinas')),
            ],
            options={
                'verbose_name': 'Área de la empresa',
                'verbose_name_plural': 'Áreas de la empresa',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del registro')),
                ('nombre', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre del cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='DatosFamiliares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del registro')),
                ('parentesco', models.IntegerField(blank=True, choices=[(1, 'Padre'), (2, 'Madre'), (3, 'Abuelo'), (4, 'Abuela'), (5, 'Nieto'), (6, 'Nieta'), (7, 'Tío'), (8, 'Tía'), (9, 'Sobrino'), (10, 'Sobrina'), (11, 'Hermano'), (12, 'Hermana'), (13, 'Primo'), (14, 'Prima'), (15, 'Cuñado'), (16, 'Cuñada'), (17, 'Esposo'), (18, 'Esposa'), (19, 'Concubino'), (20, 'Concubina'), (21, 'Hijo adoptivo'), (22, 'Hija adoptiva'), (23, 'Padre adoptivo'), (24, 'Madre adoptiva'), (25, 'Suegro'), (26, 'Suegra'), (27, 'Yerno'), (28, 'Nuera'), (29, 'Cónyuge'), (30, 'Hermanastro'), (31, 'Hermanastra'), (32, 'Abuelo materno'), (33, 'Abuela materna'), (34, 'Abuelo paterno'), (35, 'Abuela paterna'), (36, 'Hijo biológico'), (37, 'Hija biológica'), (38, 'Hermano biológico'), (39, 'Hermana biológica')], null=True, verbose_name='Parentesco')),
                ('nombres', models.CharField(blank=True, max_length=700, null=True, verbose_name='Nombres')),
                ('apellido1', models.CharField(blank=True, max_length=700, null=True, verbose_name='Primer apellido')),
                ('apellido2', models.CharField(blank=True, max_length=700, null=True, verbose_name='Segundo apellido')),
                ('cedula', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Cédula')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha nacimiento')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, db_index=True, default='', max_length=1000, null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Datos del familiar',
                'verbose_name_plural': 'Datos familiares',
            },
        ),
        migrations.CreateModel(
            name='DatosOrganizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del registro')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre de la empresa')),
                ('direccion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección de la empresa')),
                ('latitud', models.FloatField(blank=True, default=0, null=True, verbose_name='Latitud')),
                ('longitud', models.FloatField(blank=True, default=0, null=True, verbose_name='Longitud')),
                ('radio', models.FloatField(blank=True, default=0, null=True, verbose_name='Radio disponible para marcar')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleJornadaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del registro')),
                ('dia', models.IntegerField(blank=True, choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], null=True, verbose_name='Día de la semana')),
                ('comienza', models.TimeField(blank=True, null=True, verbose_name='Hora que inicia la jornada')),
                ('finaliza', models.TimeField(blank=True, null=True, verbose_name='Hora que finaliza la jornada')),
                ('motivo_entrada', models.IntegerField(blank=True, choices=[(1, 'Entrada'), (2, 'Salida almuerzo'), (3, 'Entrada almuerzo'), (4, 'Salida')], null=True, verbose_name='Motivo')),
                ('motivo_salida', models.IntegerField(blank=True, choices=[(1, 'Entrada'), (2, 'Salida almuerzo'), (3, 'Entrada almuerzo'), (4, 'Salida')], null=True, verbose_name='Motivo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleRegistroEntradaSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del registro')),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('motivo', models.IntegerField(blank=True, choices=[(1, 'Entrada'), (2, 'Salida almuerzo'), (3, 'Entrada almuerzo'), (4, 'Salida')], null=True, verbose_name='Numeración para marcar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JornadaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del registro')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JornadaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del registro')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del registro')),
                ('is_administrador_principal', models.BooleanField(default=False, verbose_name='Es administrador principal?')),
                ('is_administrador', models.BooleanField(default=False, verbose_name='Es administrador?')),
                ('is_empleado', models.BooleanField(default=False, verbose_name='Es empleado?')),
            ],
            options={
                'verbose_name': 'Perfil de persona',
                'verbose_name_plural': 'Perfiles de personas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del registro')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Salario')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio del contrato')),
                ('fecha_terminacion', models.DateField(blank=True, null=True, verbose_name='Fecha de terminación del contrato')),
                ('activo', models.BooleanField(default=False, verbose_name='Persona trabaja actualmente?')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='PrestamoSalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del registro')),
                ('salario', models.FloatField(blank=True, default=0, null=True, verbose_name='Salario del empleado')),
                ('monto', models.FloatField(blank=True, default=0, null=True, verbose_name='Monto del préstamo')),
                ('monto_libre', models.FloatField(blank=True, default=0, null=True, verbose_name='Monto libre')),
                ('cotizacion_porcentaje_dic', models.FloatField(blank=True, default=30, null=True, verbose_name='Porcentaje diciembre')),
                ('cotizacion_dic', models.FloatField(blank=True, default=0, null=True, verbose_name='Cotización diciembre')),
                ('cantidad_cuotas', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de cuotas')),
                ('motivo', models.CharField(max_length=250, verbose_name='Observación')),
            ],
            options={
                'verbose_name': 'Préstamo salario',
                'verbose_name_plural': 'Préstamos del salario',
            },
        ),
        migrations.CreateModel(
            name='RegistroEntradaSalidaDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del registro')),
                ('fecha_hora', models.DateField(blank=True, null=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registromarcadaempleado', to='administrativo.plantillapersona')),
                ('jornada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.jornadalaboral', verbose_name='Jornada del empleado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
