# Generated by Django 4.2.5 on 2023-11-04 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrativo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroentradasalidadiario',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación'),
        ),
        migrations.AddField(
            model_name='registroentradasalidadiario',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AddField(
            model_name='prestamosalario',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.persona', verbose_name='Persona'),
        ),
        migrations.AddField(
            model_name='prestamosalario',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación'),
        ),
        migrations.AddField(
            model_name='prestamosalario',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AddField(
            model_name='plantillapersona',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.area', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='plantillapersona',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.cargo', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='plantillapersona',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.persona', verbose_name='Persona'),
        ),
        migrations.AddField(
            model_name='plantillapersona',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación'),
        ),
        migrations.AddField(
            model_name='plantillapersona',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AddField(
            model_name='personaperfil',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.persona'),
        ),
        migrations.AddField(
            model_name='personaperfil',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación'),
        ),
        migrations.AddField(
            model_name='personaperfil',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AddField(
            model_name='jornadalaboral',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación'),
        ),
        migrations.AddField(
            model_name='jornadalaboral',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AddField(
            model_name='jornadaempleado',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.plantillapersona'),
        ),
        migrations.AddField(
            model_name='jornadaempleado',
            name='jornada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.jornadalaboral'),
        ),
        migrations.AddField(
            model_name='jornadaempleado',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación'),
        ),
        migrations.AddField(
            model_name='jornadaempleado',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AddField(
            model_name='detalleregistroentradasalida',
            name='dia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.registroentradasalidadiario'),
        ),
        migrations.AddField(
            model_name='detalleregistroentradasalida',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación'),
        ),
        migrations.AddField(
            model_name='detalleregistroentradasalida',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AddField(
            model_name='detallejornadalaboral',
            name='jornada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.jornadalaboral'),
        ),
        migrations.AddField(
            model_name='detallejornadalaboral',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación'),
        ),
        migrations.AddField(
            model_name='detallejornadalaboral',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AddField(
            model_name='datosorganizacion',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación'),
        ),
        migrations.AddField(
            model_name='datosorganizacion',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AddField(
            model_name='datosfamiliares',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.genero', verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='datosfamiliares',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.persona'),
        ),
        migrations.AddField(
            model_name='datosfamiliares',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación'),
        ),
        migrations.AddField(
            model_name='datosfamiliares',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AddField(
            model_name='area',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='baseapp.persona', verbose_name='Persona encargada del área'),
        ),
        migrations.AddField(
            model_name='area',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación'),
        ),
        migrations.AddField(
            model_name='area',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AddField(
            model_name='amortizacionprestamo',
            name='prestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.prestamosalario', verbose_name='Préstamo'),
        ),
        migrations.AddField(
            model_name='amortizacionprestamo',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación'),
        ),
        migrations.AddField(
            model_name='amortizacionprestamo',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
    ]
