# Generated by Django 4.2.5 on 2023-11-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaperfil',
            name='is_empleado',
        ),
        migrations.AddField(
            model_name='personaperfil',
            name='is_usuariofinal',
            field=models.BooleanField(default=False, verbose_name='Es usuario final?'),
        ),
    ]
